services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    command: python -m uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=${DOCKER_DATABASE_URL}
      - FRONTEND_ORIGINS=${FRONTEND_ORIGINS}
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "3000:8080"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
      - ./frontend/next.config.ts:/app/next.config.ts
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - ./frontend/components.json:/app/components.json
      - ./frontend/postcss.config.mjs:/app/postcss.config.mjs
      - ./frontend/eslint.config.mjs:/app/eslint.config.mjs
      - /app/node_modules
      - /app/.next
    working_dir: /app
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - DEV=true

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mdeal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
